In [2]:
import pandas as pd

In [2]:
df=pd.read_csv('co2_emissions (1).csv',sep=';')
df.head()

,make,model,vehicle_class,engine_size,cylinders,transmission,fuel_type,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb(l/100km),fuel_consumption_comb(mpg),co2_emissions
0,ACURA,ILX,COMPACT,2.0,4,AS,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS,Z,12.1,8.7,10.6,27,244

In [3]:
!apt-get install swig -y

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  swig3.0
Suggested packages:
  swig-doc swig-examples swig3.0-examples swig3.0-doc
The following NEW packages will be installed:
  swig swig3.0
0 upgraded, 2 newly installed, 0 to remove and 39 not upgraded.
Need to get 1,100 kB of archives.
After this operation, 5,822 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 swig3.0 amd64 3.0.12-1 [1,094 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 swig amd64 3.0.12-1 [6,460 B]
Fetched 1,100 kB in 1s (1,665 kB/s)
Selecting previously unselected package swig3.0.
(Reading database ... 156210 files and directories currently installed.)
Preparing to unpack .../swig3.0_3.0.12-1_amd64.deb ...
Unpacking swig3.0 (3.0.12-1) ...
Selecting previously unselected package swig.
Preparing to unpack .../swig_3.0.12-1_amd64.deb ...
Unpacking swig (3.0.12-1) ...
Setting up swig3.0 (3.0.12-1) ...
Setting up swig (3.0.12-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

In [4]:
!pip install Cython numpy

Requirement already satisfied: Cython in /usr/local/lib/python3.7/dist-packages (0.29.28)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.21.5)

In [5]:
!pip install auto-sklearn

Collecting auto-sklearn
  Downloading auto-sklearn-0.14.6.tar.gz (6.4 MB)
     |████████████████████████████████| 6.4 MB 6.6 MB/s
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (57.4.0)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (3.10.0.2)
Collecting distro
  Downloading distro-1.7.0-py3-none-any.whl (20 kB)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.21.5)
Collecting scipy>=1.7.0
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     |████████████████████████████████| 38.1 MB 311 kB/s
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.1.0)
Collecting scikit-learn<0.25.0,>=0.24.0
  Downloading scikit_learn-0.24.2-cp37-cp37m-manylinux2010_x86_64.whl (22.3 MB)
     |████████████████████████████████| 22.3 MB 1.4 MB/s
Collecting dask>=2021.12
  Downloading dask-2022.2.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 52.1 MB/s
Collecting distributed>=2012.12
  Downloading distributed-2022.2.0-py3-none-any.whl (837 kB)
     |████████████████████████████████| 837 kB 48.5 MB/s
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (3.13)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (1.3.5)
Collecting liac-arff
  Downloading liac-arff-2.5.0.tar.gz (13 kB)
Requirement already satisfied: threadpoolctl in /usr/local/lib/python3.7/dist-packages (from auto-sklearn) (3.1.0)
Collecting ConfigSpace<0.5,>=0.4.14
  Downloading ConfigSpace-0.4.21-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 36.3 MB/s
Collecting pynisher>=0.6.3
  Downloading pynisher-0.6.4.tar.gz (11 kB)
Collecting pyrfr<0.9,>=0.8.1
  Downloading pyrfr-0.8.2-cp37-cp37m-manylinux2014_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 33.9 MB/s
Collecting smac>=0.14
  Downloading smac-1.2.tar.gz (260 kB)
     |████████████████████████████████| 260 kB 59.3 MB/s
Requirement already satisfied: cython in /usr/local/lib/python3.7/dist-packages (from ConfigSpace<0.5,>=0.4.14->auto-sklearn) (0.29.28)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.7/dist-packages (from ConfigSpace<0.5,>=0.4.14->auto-sklearn) (3.0.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from dask>=2021.12->auto-sklearn) (21.3)
Requirement already satisfied: toolz>=0.8.2 in /usr/local/lib/python3.7/dist-packages (from dask>=2021.12->auto-sklearn) (0.11.2)
Requirement already satisfied: cloudpickle>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from dask>=2021.12->auto-sklearn) (1.3.0)
Collecting partd>=0.3.10
  Downloading partd-1.2.0-py3-none-any.whl (19 kB)
Collecting pyyaml
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 46.9 MB/s
Collecting fsspec>=0.6.0
  Downloading fsspec-2022.2.0-py3-none-any.whl (134 kB)
     |████████████████████████████████| 134 kB 50.6 MB/s
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from distributed>=2012.12->auto-sklearn) (2.11.3)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed>=2012.12->auto-sklearn) (1.7.0)
Requirement already satisfied: psutil>=5.0 in /usr/local/lib/python3.7/dist-packages (from distributed>=2012.12->auto-sklearn) (5.4.8)
Requirement already satisfied: zict>=0.1.3 in /usr/local/lib/python3.7/dist-packages (from distributed>=2012.12->auto-sklearn) (2.1.0)
Requirement already satisfied: tornado>=5 in /usr/local/lib/python3.7/dist-packages (from distributed>=2012.12->auto-sklearn) (5.1.1)
Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /usr/local/lib/python3.7/dist-packages (from distributed>=2012.12->auto-sklearn) (2.4.0)
Collecting cloudpickle>=1.1.1
  Downloading cloudpickle-2.0.0-py3-none-any.whl (25 kB)
Requirement already satisfied: msgpack>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from distributed>=2012.12->auto-sklearn) (1.0.3)
Requirement already satisfied: click>=6.6 in /usr/local/lib/python3.7/dist-packages (from distributed>=2012.12->auto-sklearn) (7.1.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->auto-sklearn) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->auto-sklearn) (2.8.2)
Collecting locket
  Downloading locket-0.2.1-py2.py3-none-any.whl (4.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.0->auto-sklearn) (1.15.0)
Collecting emcee>=3.0.0
  Downloading emcee-3.1.1-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 1.6 MB/s
Requirement already satisfied: heapdict in /usr/local/lib/python3.7/dist-packages (from zict>=0.1.3->distributed>=2012.12->auto-sklearn) (1.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->distributed>=2012.12->auto-sklearn) (2.0.1)
Building wheels for collected packages: auto-sklearn, pynisher, smac, liac-arff
  Building wheel for auto-sklearn (setup.py) ... done
  Created wheel for auto-sklearn: filename=auto_sklearn-0.14.6-py3-none-any.whl size=6602835 sha256=d9376792ad9796233238ec8012f082fa9ea3897243b6f8ccf265869f1465e93a
  Stored in directory: /root/.cache/pip/wheels/6a/70/48/db9c00457f87a751083ca0d5c99bf34387dde818c705bd9800
  Building wheel for pynisher (setup.py) ... done
  Created wheel for pynisher: filename=pynisher-0.6.4-py3-none-any.whl size=7043 sha256=130a0067bfffb1e45c361234f973bd1cecfafeced72ece749b310708d2073a73
  Stored in directory: /root/.cache/pip/wheels/42/71/95/7555ec3253e1ba8add72ae5febf1b015d297f3b73ba296d6f6
  Building wheel for smac (setup.py) ... done
  Created wheel for smac: filename=smac-1.2-py3-none-any.whl size=215934 sha256=5073f213a136f0c7c990ab3d45aa038b24fa37f8640b780c6daa4697f9e713d7
  Stored in directory: /root/.cache/pip/wheels/ad/95/67/6afc6b04d3715070c853d0a9d7c7b1fb822def38671dfbbb9f
  Building wheel for liac-arff (setup.py) ... done
  Created wheel for liac-arff: filename=liac_arff-2.5.0-py3-none-any.whl size=11732 sha256=73a6639be8030955a5ba82cbf4be7d66c4785834d12c198d3d7a5ba75230393b
  Stored in directory: /root/.cache/pip/wheels/1f/0f/15/332ca86cbebf25ddf98518caaf887945fbe1712b97a0f2493b
Successfully built auto-sklearn pynisher smac liac-arff
Installing collected packages: locket, pyyaml, partd, fsspec, cloudpickle, scipy, dask, scikit-learn, pyrfr, pynisher, emcee, distributed, ConfigSpace, smac, liac-arff, distro, auto-sklearn
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Attempting uninstall: cloudpickle
    Found existing installation: cloudpickle 1.3.0
    Uninstalling cloudpickle-1.3.0:
      Successfully uninstalled cloudpickle-1.3.0
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
  Attempting uninstall: dask
    Found existing installation: dask 2.12.0
    Uninstalling dask-2.12.0:
      Successfully uninstalled dask-2.12.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
  Attempting uninstall: distributed
    Found existing installation: distributed 1.25.3
    Uninstalling distributed-1.25.3:
      Successfully uninstalled distributed-1.25.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.4 requires scikit-learn>=1.0.0, but you have scikit-learn 0.24.2 which is incompatible.
gym 0.17.3 requires cloudpickle<1.7.0,>=1.2.0, but you have cloudpickle 2.0.0 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed ConfigSpace-0.4.21 auto-sklearn-0.14.6 cloudpickle-2.0.0 dask-2022.2.0 distributed-2022.2.0 distro-1.7.0 emcee-3.1.1 fsspec-2022.2.0 liac-arff-2.5.0 locket-0.2.1 partd-1.2.0 pynisher-0.6.4 pyrfr-0.8.2 pyyaml-6.0 scikit-learn-0.24.2 scipy-1.7.3 smac-1.2

In [6]:
df=pd.read_csv('co2_emissions (1).csv',sep=';')
df.head()

,make,model,vehicle_class,engine_size,cylinders,transmission,fuel_type,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb(l/100km),fuel_consumption_comb(mpg),co2_emissions
0,ACURA,ILX,COMPACT,2.0,4,AS,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS,Z,12.1,8.7,10.6,27,244

In [9]:
df[df.duplicated()]

,make,model,vehicle_class,engine_size,cylinders,transmission,fuel_type,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb(l/100km),fuel_consumption_comb(mpg),co2_emissions
1075,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS,Z,12.1,8.7,10.6,27,244
1076,ACURA,RLX,MID-SIZE,3.5,6,AS,Z,11.9,7.7,10.0,28,230
1081,ALFA ROMEO,4C,TWO-SEATER,1.8,4,AM,Z,9.7,6.9,8.4,34,193
1082,ASTON MARTIN,DB9,MINICOMPACT,5.9,12,A,Z,18.0,12.6,15.6,18,359
1084,ASTON MARTIN,V8 VANTAGE,TWO-SEATER,4.7,8,AM,Z,17.4,11.3,14.7,19,338
...,...,...,...,...,...,...,...,...,...,...,...,...
7356,TOYOTA,Tundra,PICKUP TRUCK - STANDARD,5.7,8,AS,X,17.7,13.6,15.9,18,371
7365,VOLKSWAGEN,Golf GTI,COMPACT,2.0,4,M,X,9.8,7.3,8.7,32,203
7366,VOLKSWAGEN,Jetta,COMPACT,1.4,4,AS,X,7.8,5.9,7.0,40,162
7367,VOLKSWAGEN,Jetta,COMPACT,1.4,4,M,X,7.9,5.9,7.0,40,163
7368,VOLKSWAGEN,Jetta GLI,COMPACT,2.0,4,AM,X,9.3,7.2,8.4,34,196

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.reset_index()

,index,make,model,vehicle_class,engine_size,cylinders,transmission,fuel_type,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb(l/100km),fuel_consumption_comb(mpg),co2_emissions
0,0,ACURA,ILX,COMPACT,2.0,4,AS,Z,9.9,6.7,8.5,33,196
1,1,ACURA,ILX,COMPACT,2.4,4,M,Z,11.2,7.7,9.6,29,221
2,2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV,Z,6.0,5.8,5.9,48,136
3,3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS,Z,12.7,9.1,11.1,25,255
4,4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6268,7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS,Z,10.7,7.7,9.4,30,219
6269,7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS,Z,11.2,8.3,9.9,29,232
6270,7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS,Z,11.7,8.6,10.3,27,240
6271,7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS,Z,11.2,8.3,9.9,29,232
6272,7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS,Z,12.2,8.7,10.7,26,248

In [17]:
df.head()

,make,model,vehicle_class,engine_size,cylinders,transmission,fuel_type,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb(l/100km),fuel_consumption_comb(mpg),co2_emissions
0,ACURA,ILX,COMPACT,2.0,4,AS,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS,Z,12.1,8.7,10.6,27,244

In [18]:
df.shape

(6273, 12)

In [19]:
for i in df.columns:
    if df[i].dtype=='object':
        df[i]=df[i].astype("category")
        df[i]=df[i].cat.codes

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6273 entries, 0 to 7384
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   make                            6273 non-null   int8
 1   model                           6273 non-null   int16
 2   vehicle_class                   6273 non-null   int8
 3   engine_size                     6273 non-null   float64
 4   cylinders                       6273 non-null   int64
 5   transmission                    6273 non-null   int8
 6   fuel_type                       6273 non-null   int8
 7   fuel_consumption_city           6273 non-null   float64
 8   fuel_consumption_hwy            6273 non-null   float64
 9   fuel_consumption_comb(l/100km)  6273 non-null   float64
 10  fuel_consumption_comb(mpg)      6273 non-null   int64
 11  co2_emissions                   6273 non-null   int64
dtypes: float64(4), int16(1), int64(3), int8(4)
memory usage: 428.8 KB

In [21]:
df.head()

,make,model,vehicle_class,engine_size,cylinders,transmission,fuel_type,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb(l/100km),fuel_consumption_comb(mpg),co2_emissions
0,0,1057,0,2.0,4,2,4,9.9,6.7,8.5,33,196
1,0,1057,0,2.4,4,4,4,11.2,7.7,9.6,29,221
2,0,1058,0,1.5,4,3,4,6.0,5.8,5.9,48,136
3,0,1233,11,3.5,6,2,4,12.7,9.1,11.1,25,255
4,0,1499,11,3.5,6,2,4,12.1,8.7,10.6,27,244

In [ ]:
df.make.value_counts()

In [24]:
x=df.drop("co2_emissions",axis=1)
y=df['co2_emissions']

In [25]:
x.head()

,make,model,vehicle_class,engine_size,cylinders,transmission,fuel_type,fuel_consumption_city,fuel_consumption_hwy,fuel_consumption_comb(l/100km),fuel_consumption_comb(mpg)
0,0,1057,0,2.0,4,2,4,9.9,6.7,8.5,33
1,0,1057,0,2.4,4,4,4,11.2,7.7,9.6,29
2,0,1058,0,1.5,4,3,4,6.0,5.8,5.9,48
3,0,1233,11,3.5,6,2,4,12.7,9.1,11.1,25
4,0,1499,11,3.5,6,2,4,12.1,8.7,10.6,27

In [26]:
y.head()

0    196
1    221
2    136
3    255
4    244
Name: co2_emissions, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=7)

In [29]:
import autosklearn.regression as reg

In [30]:
model=reg.AutoSklearnRegressor(time_left_for_this_task=120,per_run_time_limit=40)

In [31]:
model.fit(x_train,y_train)

AutoSklearnRegressor(per_run_time_limit=40, time_left_for_this_task=120)

In [32]:
pred=model.predict(x_test)

In [33]:
pred

array([312.77835083, 357.06362915, 273.89988708, ..., 271.05020142,
       265.30186462, 280.2720108 ])

In [37]:
from sklearn.metrics import r2_score

In [38]:
r2_score(y_test,pred)

0.9956133402969692

In [39]:
print(model.show_models())

{5: {'model_id': 5, 'rank': 1, 'cost': 0.0029710270677550943, 'ensemble_weight': 0.58, 'data_preprocessor': <autosklearn.pipeline.components.data_preprocessing.DataPreprocessorChoice object at 0x7f644bf38c10>, 'feature_preprocessor': <autosklearn.pipeline.components.feature_preprocessing.FeaturePreprocessorChoice object at 0x7f644bf9a1d0>, 'regressor': <autosklearn.pipeline.components.regression.RegressorChoice object at 0x7f644bf9a410>, 'sklearn_regressor': HistGradientBoostingRegressor(l2_regularization=5.997418027353535e-10,
                              learning_rate=0.12286466971783992, max_iter=512,
                              max_leaf_nodes=26, min_samples_leaf=8,
                              n_iter_no_change=0, random_state=1,
                              validation_fraction=None, warm_start=True)}, 8: {'model_id': 8, 'rank': 2, 'cost': 0.0031761229060893736, 'ensemble_weight': 0.42, 'data_preprocessor': <autosklearn.pipeline.components.data_preprocessing.DataPreprocessorChoice object at 0x7f644bf38850>, 'feature_preprocessor': <autosklearn.pipeline.components.feature_preprocessing.FeaturePreprocessorChoice object at 0x7f644a8d15d0>, 'regressor': <autosklearn.pipeline.components.regression.RegressorChoice object at 0x7f644bf9ac50>, 'sklearn_regressor': ExtraTreesRegressor(max_features=0.9797793053686011, min_samples_split=4,
                    n_estimators=512, n_jobs=1, random_state=1,
                    warm_start=True)}}